# Generated by Django 3.0.6 on 2020-05-28 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='list_id',
            new_name='listing_id',
        ),
    ]
