# Generated by Django 3.0.6 on 2020-05-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200525_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='garage',
        ),
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
